version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    image: "php:7.4.29-fpm-alpine3.15"
    volumes:
      - .:/app/

#  postgres:
#    image: "postgres:14.2"
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: "db"
#      POSTGRES_HOST_AUTH_METHOD: "trust"